Repository anon-aadhaar/anon-aadhaar, pull requests merged in 2023-12, with the labels that each got.

#104 fix: testing mode
  CHANGELOG.md
  package.json
  packages/anon-aadhaar-contracts/package.json
  packages/anon-aadhaar-pcd/package.json
  packages/anon-aadhaar-pcd/src/pcd.ts
  packages/anon-aadhaar-react/package.json
  packages/anon-aadhaar-react/src/components/LogInWithAnonAadhaar.tsx
  packages/anon-aadhaar-react/src/components/ProveButton.tsx
  packages/anon-aadhaar-react/src/components/ProveModal.tsx
  packages/anon-aadhaar-react/src/hooks/useAnonAadhaar.ts
  packages/anon-aadhaar-react/src/provider/AnonAadhaarProvider.tsx
  packages/anon-aadhaar-react/src/util.ts
  packages/anon-aadhaar-react/test/hook.test.tsx
Labels: enhancement

#106 fix(chore): react dependencies (axios, buffer)
  CHANGELOG.md
  packages/anon-aadhaar-pcd/package.json
  packages/anon-aadhaar-pcd/src/extractWitness.ts
  packages/anon-aadhaar-pcd/src/pcd.ts
  packages/anon-aadhaar-pcd/src/prover.ts
  packages/anon-aadhaar-pcd/src/utils.ts
  packages/anon-aadhaar-react/package.json
  packages/anon-aadhaar-react/src/components/ButtonLogo.ts
  packages/anon-aadhaar-react/src/components/ErrorToast.tsx
  packages/anon-aadhaar-react/src/components/LogInWithAnonAadhaar.tsx
  packages/anon-aadhaar-react/src/components/ProveButton.tsx
  packages/anon-aadhaar-react/src/components/ProveModal.tsx
  packages/anon-aadhaar-react/src/util.ts
Labels: bug

#109 Feat/script gen pdf improvement
  CHANGELOG.md
  README.md
  packages/anon-aadhaar-pcd/script/setup-dev.sh
Labels: bug, enhancement

#110 fix(chore): UI improvments + UX fix
  CHANGELOG.md
  package.json
  packages/anon-aadhaar-contracts/package.json
  packages/anon-aadhaar-pcd/package.json
  packages/anon-aadhaar-react/package.json
  packages/anon-aadhaar-react/src/components/LogInWithAnonAadhaar.tsx
  packages/anon-aadhaar-react/src/components/ProveButton.tsx
  packages/anon-aadhaar-react/src/components/ProveModal.tsx
  packages/anon-aadhaar-react/src/util.ts
Labels: enhancement

#111 fix(chore): change scripts to not includ contracts gen when dev-setup
  CHANGELOG.md
  package.json
  packages/anon-aadhaar-contracts/test/Verifier.ts
  packages/anon-aadhaar-contracts/test/util.ts
  packages/anon-aadhaar-pcd/script/setup-dev.sh
Labels: contracts

#117 fix: localhost mode
  CHANGELOG.md
  package.json
  packages/anon-aadhaar-contracts/package.json
  packages/anon-aadhaar-pcd/package.json
  packages/anon-aadhaar-pcd/src/pcd.ts
  packages/anon-aadhaar-react/package.json
  packages/anon-aadhaar-react/src/components/ProveModal.tsx
  packages/anon-aadhaar-react/src/prove.ts
  packages/anon-aadhaar-react/src/provider/AnonAadhaarProvider.tsx
  packages/anon-aadhaar-react/test/pcd.test.ts
Labels: Test

#118 fix(chore): remove subtle from src
  CHANGELOG.md
  package.json
  packages/anon-aadhaar-contracts/package.json
  packages/anon-aadhaar-contracts/test/Verifier.ts
  packages/anon-aadhaar-pcd/package.json
  packages/anon-aadhaar-pcd/script/generateInput.ts
  packages/anon-aadhaar-pcd/src/utils.ts
  packages/anon-aadhaar-pcd/test/nullifier.test.ts
  packages/anon-aadhaar-pcd/test/pcd.test.ts
  packages/anon-aadhaar-pcd/test/utils.ts
  packages/anon-aadhaar-react/package.json
  packages/anon-aadhaar-react/test/hook.test.tsx
  packages/anon-aadhaar-react/test/pcd.test.ts
Labels: bug
